name: "Terraform Plan Preview"

inputs:
  plan-stdout:
    require: true
  plan-outcome:
    require: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Plan 📖\`${{ inputs.plan-outcome }}\`
          
          \`\`\`\n
          ${{ inputs.plan-stdout }}
          \`\`\`
          `;

          await core.summary.addRaw(output).write();
