name: "Setup Terraform"

inputs:
  terraform-version-file:
    required: false
    type: string
    default: ".terraform-version"

runs:
  using: "composite"
  steps:
    - name: Get Terraform Version
      id: terraform_version
      run: echo value="$(cat ${{ inputs.terraform-version-file }})" >> "$GITHUB_OUTPUT"
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ steps.terraform_version.outputs.value }}
