name: Commit Javadoc to the branch

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "javadocs"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download Artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: source

      - name: Create staging directory
        run: mkdir staging

      - name: Copy to versioned page
        run: cp -r source staging/${{ inputs.project-version }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
