name: Go Build
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      enable-cache:
        type: boolean
        required: false
        default: true
      build-arguments:
        type: string
        required: false
        default: "build"
      go-filepath:
        type: string
        required: true
      target-os:
        type: string
        description: |
          The target operating system for the build.
          This value will be set to GOOS environment variable.
          See https://go.dev/doc/install/source#environment
        required: false
      target-arch:
        type: string
        description: |
          The target architecture for the build.
          This value will be set to GOARCH environment variable.
          See https://go.dev/doc/install/source#environment
        required: false
      output-filepath:
        type: string
        required: true
      package-name:
        required: false
        type: string
        default: "Package"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      working-dir:
        required: false
        type: string
        default: "."
      go-version:
        required: false
        type: string  

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: Siroshun09/gh-actions-workflows/.github/actions/checkout@v1
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-setup@v1
        with:
          enable-cache: ${{ inputs.enable-cache }}
          go-version: ${{ inputs.go-version }}
          working-dir: ${{ inputs.working-dir }}
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-build@v1
        with:
          build-arguments: ${{ inputs.build-arguments }}
          go-filepath: ${{ inputs.go-filepath }}
          target-os: ${{ inputs.target-os }}
          target-arch: ${{ inputs.target-arch }}
          output-filepath: ${{ inputs.output-filepath }}
          working-dir: ${{ inputs.working-dir }}
      - name: "Upload artifacts"
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        continue-on-error: true
        with:
          name: ${{ inputs.package-name }}-${{ runner.os }}-${{ runner.arch }}
          path: ${{ inputs.working-dir }}/${{ inputs.output-filepath }}
