name: Go Lint
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      go-version:
        required: false
        type: string
      golangci-lint-version:
        required: true
        type: string
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: "Set up Go"
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.working-dir }}/go.mod
          cache: ${{ inputs.enable-cache }}
          cache-dependency-path: |
            ${{ inputs.working-dir }}/go.sum
      - name: "Lint"
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9.0.0
        with:
          version: ${{ inputs.golangci-lint-version }}
          working-directory: ${{ inputs.working-dir }}
          args: ${{ inputs.additional-arguments }}
