name: Go Lint
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      go-version:
        required: false
        type: string
      golangci-lint-version:
        required: false
        type: string
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  lint:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: Siroshun09/gh-actions-workflows/.github/actions/checkout@v1
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-setup@v1
        with:
          enable-cache: ${{ inputs.enable-cache }}
          go-version: ${{ inputs.go-version }}
          working-dir: ${{ inputs.working-dir }}
      - name: "Lint"
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: ${{ inputs.golangci-lint-version }}
          version-file: .golangci-lint-version
          working-directory: ${{ inputs.working-dir }}
          args: ${{ inputs.additional-arguments }}
