name: Go Lint
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      go-version:
        required: false
        type: string
      golangci-lint-version:
        required: true
        type: string
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Set up Go"
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.working-dir }}/go.mod
          cache: ${{ inputs.enable-cache }}
          cache-dependency-path: |
            ${{ inputs.working-dir }}/go.sum
      - name: "Lint"
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          version: ${{ inputs.golangci-lint-version }}
          working-directory: ${{ inputs.working-dir }}
          args: ${{ inputs.additional-arguments }}
