name: Go Test
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      upload-results:
        required: false
        type: boolean
      check-name:
        type: string
        description: |
          The name of the check displayed in GitHub Actions.
        required: false
      working-dir:
        required: false
        type: string
        default: "."
      go-version:
        required: false
        type: string
      gotestsum-version:
        required: false
        type: string
      gotestsum-arguments:
        type: string
        description: |
          The arguments to pass to gotestsum command.
        required: false

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: Siroshun09/gh-actions-workflows/.github/actions/checkout@v1
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-setup@v1
        with:
          enable-cache: ${{ inputs.enable-cache }}
          go-version: ${{ inputs.go-version }}
          working-dir: ${{ inputs.working-dir }}
      - uses: Siroshun09/gh-actions-workflows/.github/actions/go-test@v1
        with:
          additional-arguments: ${{ inputs.additional-arguments }}
          upload-results: ${{ inputs.upload-results }}
          check-name: ${{ inputs.check-name }}
          gotestsum-version: ${{ inputs.gotestsum-version }}
          gotestsum-arguments: ${{ inputs.gotestsum-arguments }}
          working-dir: ${{ inputs.working-dir }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
