name: Go Build
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      upload-results:
        required: false
        type: boolean
        default: false
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: "Set up Go"
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ${{ inputs.working-dir }}/go.mod
          cache: ${{ inputs.enable-cache }}
          cache-dependency-path: |
            ${{ inputs.working-dir }}/go.sum
      - name: "Test"
        working-directory: ${{ inputs.working-dir }}
        run: |
          go run gotest.tools/gotestsum@v1.12.0 --junitfile ~/test-results.xml ${{ inputs.additional-arguments }}
      - name: "Upload Results"
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        if: ${{ inputs.upload-results && (success() || failure()) }}
        continue-on-error: true
        with:
          report_paths: ~/test-results.xml
          check_name: Test Report
