name: Go Test
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: "ubuntu-latest"
      enable-cache:
        type: boolean
        required: false
        default: true
      additional-arguments:
        type: string
        required: false
        default: ""
      upload-results:
        required: false
        type: boolean
        default: false
      working-dir:
        required: false
        type: string
        default: "."
      go-version:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "Set up Go"
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.working-dir }}/go.mod
          cache: ${{ inputs.enable-cache }}
          cache-dependency-path: |
            ${{ inputs.working-dir }}/go.sum
      - name: "Test"
        working-directory: ${{ inputs.working-dir }}
        run: |
          go run gotest.tools/gotestsum@v1.12.3 --junitfile ~/test-results.xml ${{ inputs.additional-arguments }}
      - name: "Upload Results"
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: ${{ inputs.upload-results && (success() || failure()) }}
        continue-on-error: true
        with:
          report_paths: ~/test-results.xml
          check_name: Test Report
