name: Generate Javadoc (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      gradle-arguments:
        required: false
        type: string
        default: "javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./build/docs"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      cache-disabled:
        required: false
        type: boolean
        default: false
      caching-refs:
        required: false
        type: string
        default: |
          refs/heads/main
          refs/heads/master
          refs/heads/develop
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1
        with:
          cache-disabled: ${{ inputs.cache-disabled }}
          cache-read-only: ${{ !contains(inputs.caching-refs, github.ref) }}
      - name: Build with Gradle
        working-directory: ${{ inputs.working-dir }}
        run: |
          chmod +x ./gradlew
          ./gradlew ${{ inputs.gradle-arguments }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
