name: Generate Javadoc (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      gradle-arguments:
        required: false
        type: string
        default: "javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./build/docs"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      cache-disabled:
        required: false
        type: boolean
        default: false
      caching-refs:
        required: false
        type: string
        default: |
          refs/heads/main
          refs/heads/master
          refs/heads/develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3.12.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - run: chmod +x ./gradlew
      - name: Generate Javadoc
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: ${{ inputs.gradle-arguments }}
          cache-disabled: ${{ inputs.cache-disabled }}
          cache-read-only: ${{ !contains(inputs.caching-refs, github.ref) }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
