name: Generate Javadoc (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      gradle-arguments:
        required: false
        type: string
        default: "javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./build/docs"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3.5.1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - run: chmod +x ./gradlew
      - name: Generate Javadoc
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments: ${{ inputs.gradle-arguments }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
