name: Generate Javadoc (Maven)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      maven-arguments:
        required: false
        type: string
        default: "javadoc::javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./target/site/apidocs"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Generate Javadoc
        working-directory: ${{ inputs.working-dir }}
        run: mvn -B --file pom.xml -Djava.version=${{ inputs.java-version }} ${{ inputs.maven-arguments }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
