name: Generate Javadoc (Maven)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      maven-arguments:
        required: false
        type: string
        default: "javadoc::javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./target/site/apidocs"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Generate Javadoc
        working-directory: ${{ inputs.working-dir }}
        run: mvn -B --file pom.xml -Djava.version=${{ inputs.java-version }} ${{ inputs.maven-arguments }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
