name: Generate Javadoc (Maven)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      maven-arguments:
        required: false
        type: string
        default: "javadoc::javadoc"
      artifact-name:
        required: false
        type: string
        default: "Javadoc"
      javadoc-directory:
        required: false
        type: string
        default: "./target/site/apidocs"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      working-dir:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Generate Javadoc
        working-directory: ${{ inputs.working-dir }}
        run: mvn -B --file pom.xml -Djava.version=${{ inputs.java-version }} ${{ inputs.maven-arguments }}
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.javadoc-directory }}
