name: Terraform Plan

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      terraform-version-file:
        required: false
        type: string
        default: ".terraform-version"
    secrets:
      TERRAFORM_PLAN_ENV:
        required: true

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Mask Passed Environment Variables
        run: |
          echo "$TERRAFORM_PLAN_ENV" | jq -r 'to_entries[] | "::add-mask::\(.value)"' | while read -r line; do
            echo "$line"
          done
        env:
          TERRAFORM_PLAN_ENV: ${{ secrets.TERRAFORM_PLAN_ENV }}

      - name: Get Terraform Version
        id: terraform_version
        run: echo value="$(cat ${{ inputs.terraform-version-file }})" >> "$GITHUB_OUTPUT"
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ steps.terraform_version.outputs.value }}

      - name: Format Check
        id: fmt
        working-directory: ${{ inputs.working-directory }}
        run: terraform fmt -check
        continue-on-error: true

      - name: Init
        id: init
        working-directory: ${{ inputs.working-directory }}
        run: terraform init -input=false

      - name: Validate
        id: validate
        working-directory: ${{ inputs.working-directory }}
        run: terraform validate -no-color
        continue-on-error: true

      - name: Plan
        id: plan
        working-directory: ${{ inputs.working-directory }}
        env: ${{ fromJSON(secrets.TERRAFORM_PLAN_ENV) }}
        run: terraform plan -no-color -input=false

      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Terraform Plan Result for \`${{ inputs.working-directory }}\`

            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`

            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`

            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            \`\`\`\n
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            `;

            await core.summary
              .addRaw(output)
              .write();
